---
- name: Check if tickstack is set
  become: true
  stat:
    path: /etc/telegraf/telegraf.conf
  register: telegraf_status
  tags: gitlab

- name: Create directory for tick stack volumes
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0775
  when: telegraf_status.stat.exists == False
  with_items:
    - /etc/telegraf/
  tags: tick_stack

- name: Deploy config files for tick stack
  become: true
  template:
    src: "{{ item }}.conf.j2"
    dest: "/etc/{{ item }}/{{ item }}.conf"
    owner: root
    group: root
    mode: 0755
  when: telegraf_status.stat.exists == False
  with_items:
    - telegraf
  tags: tick_stack
