---
- name: Synchronize microservices dockerfile
  synchronize:
    src: "{{ playbook_dir }}/../src/{{ item }}"
    dest: "/home/{{ ansible_user_id }}/"
  loop:
    - docker
    - api-authentication
  tags: authentication

- name: Deploy environement variables
  become: true
  template:
    src: env.j2
    dest: "/home/{{ ansible_user_id }}/api-authentication/.env"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0644'
  tags: authentication

- name: Deploy oauth public key
  become: true
  template:
    src: oauth-public.j2
    dest: "/home/{{ ansible_user_id }}/api-authentication/storage/oauth-public.key"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0644'
  tags: authentication

- name: Deploy oauth private key
  become: true
  template:
    src: oauth-private.j2
    dest: "/home/{{ ansible_user_id }}/api-authentication/storage/oauth-private.key"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0644'
  tags: authentication

- name: Build php-fpm dockerfile
  become: true
  docker_image:
    build:
      path: "/home/{{ ansible_user_id }}/docker/php-fpm/"
      pull: yes
    name: php-fpm
    repository: 127.0.0.1:5000/php-fpm
    tag: latest
    push: yes
    source: build
    force_absent: yes
    force_tag: yes
    force_source: yes
  tags: authentication

- name: Build nginx dockerfile
  become: true
  docker_image:
    build:
      path: "/home/{{ ansible_user_id }}/docker/nginx/"
      args:
        PHP_UPSTREAM_CONTAINER: "authentication_php-fpm"
        PHP_UPSTREAM_PORT: 9000
      pull: yes
    name: "authentication_nginx"
    repository: "127.0.0.1:5000/authentication_nginx"
    tag: latest
    push: yes
    source: build
    force_absent: yes
    force_tag: yes
    force_source: yes
  tags: authentication
